### ISSUE TITLE
Permissions Super-Epic

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/multi-repo-issue#100]
## User Stories

- **Market: Exclusivity.** MarketA wants to be the exclusive market selling assetB. Other markets can't see assetB's metadata, and don't show assetB. (Versus the default, where any asset published anywhere can be seen by any assets.)
- **Restrict consume.** Alice publishes data assetA. Anyone can buy/sell assetA. Only employees of CompanyB & CompanyC can consume it
- **Market: Restrict X**
  - **Market: Restrict discovery.** MarketA only lets employees of CompanyB & CompanyC to browse, search and filter assets. 
  - **Market: Restrict publish.** MarketA only lets employees of CompanyD to publish assets 
  - **Market: Restrict buy.** MarketA only lets employees of CompanyE to buy assets 
- **Toggle 'is consumable'.** From Market GUI, publisher turns 'is consumable' off. The market GUI shows that the asset isn't currently consumable. If someone with the asset tries to consume, GUI won't let it, and backend won't let it.

## Issues

Here are github issues/epics to implement the user stories above.

**Market: Exclusivity**
- [x] Encrypt DDO backend
- [x] Encrypt DDO frontend [react#264](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/react/264)
- [x] MarketX filters out encrypted assets that it doesn't have the private key for
- (add to me)

**Restrict consume**
- [ ] RBAC Server for consume [multi-repo-issue#76](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/multi-repo-issue/76)
- (add to me)

**Market: Restrict X** 
- (add to me)

**Toggle 'is consumable'**
- As a data seller, I would like to disable consume for certain assets during certain activities like maintenance or downtime [market#452](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/market/452)
