### ISSUE TITLE
Ocean Market supports $OCEAN-backed stablecoin

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/multi-repo-issue#118]
**Motivations**

- Main: For stakers, reduce risk exposure to fluctuations in $OCEAN itself
- Also: Fewer variables for a user to have to consider when engaging with Ocean Market
 
**TODOs for this issue**

- [ ] An $OCEAN-backed _perpetual_ stablecoin is deployed to Eth mainnet (with 3rd party collaborators). Note: can't use ODollar as it's non-perpetual
- [ ] Stablecoin is bridged to Polygon, including good documentation / low-friction app for users
- [ ] In Polygon, create a pool to easily swap to the stablecoin (from mETH or other). Add liquidity so slippage is low.
- [ ] Ensure completed elsewhere: oceanprotocol/market#468
- [ ] Ensure completed elsewhere: oceanprotocol/market#467
- [ ] Have Ocean Market base token = stablecoin, in both Eth mainnet and Polygon. It would still need to support OCEAN in older pools (possible to have both due to market 467 work above)

**Comment by trentmc** [comment]
Good points. Thanks for changing to epic. I moved it to multi repo.
