### ISSUE TITLE
[EPIC] Ocean Market support for Compute-to-Data, while solving algorithm trust issue

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/multi-repo-issue#31]
The libraries and smart contracts support Compute-to-Data.

We had Compute-to-Data built into Ocean Market and could have shipped it in the V3.0 release. 

But there was fundamental problem: the buyer could put in any algorithm they wanted. So they could simply do a copy and get all the results, breaking the whole point of Compute-to-Data in the first place.

There are two approaches to handle this.
1. Pre-whitelisted algorithm
2. Consumer proposes an algorithm, and it gets vetted by Data Provider

Compute-to-data / DDO already supports both in the backend.

Of them, (1) is simpler for workflow (and therefore changes to Ocean Market GUI). Here's a set of possible steps to build.
- there's already support for whitelisting algorithms / scripts in the DDO
- start with a couple super-simple algorithms that can be run on files
- and specify the file format

My suggestion:
- [ ] make the file format a list of numbers; example below. Support these algorithms: average, median. Wire everything up and make it work (this won't be trivial:)
- [ ] fix other Compute-to-data bugs. They're included as part of this epic.
- [ ] once that's shipped, then the next step is to support the simplest-possible AI modeling algs. My recommendation is >=2 linear regression and a couple linear classification algorithms from scikit-learn 
```
23.3
5433.9
23293.322
32
10000
1e9
.9332
```

**Comment by w1kke** [comment]
What happened to the solution of this bounty?
https://gitcoin.co/issue/oceanprotocol/ocean-bounties/27/4461
It was supposed to prevent private data leakage and enabled the check of the outputs before they were handed back to the algorithm provider. Is this not on the table anymore to have another check by the data provider before handing back the results?

**Comment by alexcos20** [comment]
I will take it with Robin further

**Comment by mihaisc** [comment]
This epic is old and most of the topics are fixed, deprecated or have changed in the meantime. The new epic that handles market support for compute to data is [here](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/multi-repo-issue/53)
