### ISSUE TITLE
[EPIC] Address IP rights violation & sensitive data

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/multi-repo-issue#34]
IP rights violation is copyright infringement. We want to address this. Examples: (a) people selling access to movies that they don't have the rights to. If they did have the rights, for example if they were the movie studio - that's fine. (b) selling CPU benchmarking specs. (c)  Copying someone else's dataset and re-posting it as their own.

We also have to address when sensitive data is posted. This includes personally identifiable information, hate speech, etc.

**Done**
- [x] Publisher/owner search. Market#187. Why: drives publisher reputation. Note: also in [Rug pulls epic](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/multi-repo-issue/30)
- [x] Datapartners list. [Market-189](https://github.com/oceanprotocol/market/issues/189)
- [x] Purgatory list (IP violation, sensitive data). [Market-229](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/market/229). Note: also in "Rug Pull" Epic.

**In progress**
- [ ] Help publisher credibility by linking Eth address to 3Box (which links to other profiles). [Market-240](https://github.com/oceanprotocol/market/issues/240). Note: also in "IP Violation" epic [Mihai]

**Agreed-upon backlog**
[Empty]

**Possible tactics, to discuss more, only add to backlog if agreed**
- People who have consumed data can give a rating. [Multi-repo-32](https://github.com/oceanprotocol/multi-repo-issue/issues/32) [Mihai]
- Custom badges for accounts in Ocean Market. [Market-252](https://github.com/oceanprotocol/market/issues/252)
- ...
- Help publisher credibility by linking Eth address to ENS [Market-188](https://github.com/oceanprotocol/Market/issues/188). Note: Note: also in "Rug Pull" Epic. 
- Escalation / arbitration via Aragon Protocol. Why: Need a way for purgatory feature to scale, without intervention by team. Tech spike needed first
- Can flag a dataset from Ocean Market itself. Before we do this, we should be able to handle flagging at scale better, e.g. via escalation / arbitration via Aragon. 
- Leverage Boson Protocol's dispute-resolution mechanics 
- Retire datapartners list (when the time is right)
- Community-maintained verified list of publishers, or datatokens. [Here's one, as a dataset!](https://twitter.com/realdatawhale/status/1322932804049580036?s=21)

**More Notes**
- "[If we remove content from Ocean Market] then we are judge and executioner, but we need to stay neutral. So we should not remove or hide stuff, but have a flag reported: true in DDO and in that case show a warning banner atop the asset, “We have received reports of …“. We could still block adding liquidity or such, but removing is critical and sets a precedent. In any case this all needs to be transparent, we can’t decide in the background based on some tweets to take down data sets. Community-maintained lists in a public GitHub repo would be one way. Say, we have some deny list, then this can only be community-managed and in the open" (Matthias)
- "Agreed with Matthias, adding proper annotations to datasets would be sufficient, make it very clear visually and either disable pool actions or warn user for the reported datasets" (Samer)
- GDoc with more ideas on [Reputation Verification Approaches](https://docs.google.com/document/d/1s0I5Us6yiMc3kP1sl8x2vkneW4A9Fl7X6YF5bHi5oNw/edit#) (Trent)

**Comment by trentmc** [comment]
It was meant to be open already. Rectified.
