### ISSUE TITLE
Consumption / Download of Large Files (over 400MB - 500MB) Fails on Rinkeby and Mainnet Marketplace

### ISSUE THREAD

**Issue by kaimeinke** [oceanprotocol/multi-repo-issue#55]
What needs to be done:
- [ ] Fix provider side - [provider #40](https://github.com/oceanprotocol/provider/issues/40)
- [ ] Develop UX flow for market
- [ ] Fix market side - [market #314](https://github.com/oceanprotocol/market/issues/314)

--

Dear DEV-Team,

i am currently testing for an IDO with a new publisher on the Ocean Market. During the initial tests we discovered that large files with a size of approx. 5 GB can not be downloaded / consumed. This is a blocker for the IDO.

To reproduce the issue I created three pools on Rinkeby Ocean Market.

0. https://market.oceanprotocol.com/asset/did:op:e115a919B9eb125BBEa1Ff37c22Ab725B63c1335
1. https://market.oceanprotocol.com/asset/did:op:83c92519f4A791DdF3f8ae0C6912ED3D05953349
2. https://market.oceanprotocol.com/asset/did:op:1044c915af3d0A2456AC3F1F241393ae725D89c9

Within these pools two 5GB test files should be available for consumption. One TXT file and one ZIP file.

The files are currently hosted, just for testing purposes, on my webspace and are 100% available and downloadable via direct links. They were also detected correctly during the publishing process.

0. https://data-brokers.de/wp-content/uploads/2020/11/test5gb.txt
1. https://data-brokers.de/wp-content/uploads/2020/11/test5gb.txt
2. https://data-brokers.de/wp-content/uploads/2020/11/test5gb.zip

I attach what I could see from the developer console. 

Any advice / fix / communication would be highly appreciated as we need to postpone the IDO as it seems if the market does not offer the desired reliability at this moment. We would not be happy to launch this without a successful test.

Thanks a lot and all the best
Kai 

![2020-12-16 11_09_13-](https://user-images.githubusercontent.com/59994024/102336329-51cb0700-3f91-11eb-888b-1b2fe047b7db.png)

![2020-12-16 11_09_48-Explorer](https://user-images.githubusercontent.com/59994024/102336351-58f21500-3f91-11eb-9919-fbb7e6dd056c.png)

![2020-12-16 11_11_29-Einstellungen](https://user-images.githubusercontent.com/59994024/102336364-5d1e3280-3f91-11eb-8d48-86cfff5fad18.png)
