### ISSUE TITLE
[EPIC] Support Moonbeam; datasets *are* siloed

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/multi-repo-issue#66]
Aim of this issue: deploy to Moonbeam with basic needs met, so that people can buy & sell with real value. It can be janky, that's ok. [Here's a follow-up issue, where datasets are *not* siloed](https://github.com/oceanprotocol/multi-repo-issue/issues/67) and in general it will be less janky.

TODOs:
- [ ] *Some* means for people to bridge OCEAN between Eth mainnet and Moonbeam. It doesn't need to be "pretty".
- [ ] Deploy Ocean (V3) smart contracts to Moonbeam
- [ ] Deploy a new version of Ocean components for Moonbeam network, just as we have for Eth mainnet, Ropsten, etc. This includes: Ocean Market, Aquarius, Provider, something for TheGraph?, other?
- [ ] Write a blog post that sets expectations. It describes what was done; and what the longer-term goals are.

**Comment by trentmc** [comment]
Moonbeam will come later.

What will come sooner:
https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/multi-repo-issue/77
