### ISSUE TITLE
[EPIC] Metadata DDO.sol -> DT "blob" field. Support update blob.

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/multi-repo-issue#68]
Motivation: having a separate contract for metadata adds extra complexity, both in code and in peoples' mental models. The metadata could easily be with the ERC20 datatoken smart contract itself. By doing so it would be simpler, more maintainable, easier to understand.

How: Datatoken contract already has a `blob` field. Store metadata in there.

- Concern: Trent was worried that it's a huge pain to search across >>1 datatoken contracts in order to populate a metadata cache (Aquarius). 
- Solution: Alex reassured Trent that this can be fairly efficient // not expensive, especially because the datatoken factory has records / logs of all DT contracts that have been deployed.

TODOs:
- [ ] Finalize design
- [ ] Update contracts repo
- [ ] Update ocean.js
- [ ] Update ocean.py
- [ ] Update react and market
- [ ] Update docs.oceanprotocol.com and other documentation (anywhere we talk about Ocean architecture)

**Comment by kremalicious** [comment]
To me the ideal solution would be to kill the metadata contract and store json files in IPFS/Arweave/whatever, and then reference that in the ERC721 metadata. As this issue is labeled as v4 not sure what's supposed to happen here

**Comment by kaimeinke** [comment]
This has been exactly the solution Pierre Gronlier, CTO of Gaia-X, has proposed during previous talks. @trentmc has voiced an opinion on that.
