### ISSUE TITLE
Deploy on Matic / Polygon (datasets siloed)

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/multi-repo-issue#77]
- [x] test bridge of OCEAN between Eth mainnet and Matic mainnet [Dimo]
- [x] **ready except PR** document bridge usage for users [Dimo] #78
- [X] deploy smart contracts [Alex] PR : (https://github.com/oceanprotocol/contracts/pull/268)
- [x] deploy aquarius [Marian]  --- https://aquarius.polygon.oceanprotocol.com  
- [x] deploy provider [Marian]  --- https://provider.polygon.oceanprotocol.com
- [X] create subgraph [Alex] PR: (https://github.com/oceanprotocol/ocean-subgraph/pull/32)
- [x] deploy graph [Marian] --- https://subgraph.polygon.oceanprotocol.com
- [x] update ocean.js to bump ocean-contracts library & new urls for config helper [Mihai]
- [x] update ocean.py to bump ocean-contracts library [Trent]
- [x] test market [Dimo][Mihai] #82
- [x] **ready except PR** update [docs for supported networks](https://docs.oceanprotocol.com/concepts/networks/)  to include components running in Matic [Dimo]  **(FIXME insert PR url)**
- [x] play with deploying our own node, and document the experience (not *needed, but nice). [Info](https://docs.matic.network/docs/validate/mainnet/validator-guide/) [Marian]
- [x] Add banner to publish page : "Note: Only republish datatokens from Ethereum mainnet here if there is <1000 OCEAN liquidity in the original pool. Doing otherwise will lead to purgatory".
- [x] Ensure purgatory functionality https://github.com/oceanprotocol/multi-repo-issue/issues/86
- [x] Update purgatory rules https://github.com/oceanprotocol/list-purgatory/issues/34
- [x] 3Box integration https://github.com/oceanprotocol/multi-repo-issue/issues/89
- [x] Merge market branch https://github.com/oceanprotocol/market/pull/433

[Here's a follow-up issue, where datasets are not siloed](https://github.com/oceanprotocol/multi-repo-issue/issues/67).

**Comment by DimitarSD** [comment]
@trentmc @mihaisc The Matic's bridge is really easy to use and very straightforward in terms of steps. However, since the testing is happening on the Mainnet the transfers (from Ethereum to Matic) requires gas (it was around $17, now it's around $22). I didn't take that into consideration yesterday, and I currently don't have any Ocean tokens or Eth to test with. Might be better if someone else does the test cuz otherwise we'll pay double the gas costs just for transferring and testing with an account of my own. Any suggestions on this block?

**Comment by trentmc** [comment]
@md00ux what's ETA for deploying aquarius, provider, graph? Thank you!

**Comment by md00ux** [comment]
@trentmc, I have prepared the deployment files. 
Graph-node is deployed, we should have the rest of components in ~1h from now.,

**Comment by mihaisc** [comment]
I transfered 300 ocean from eth main to matic main. The process was smooth but users may be confused by the following 
1. Metamask shows that i have 0.1 eth . I need to add custom token to see ocean ( contract addr : 0x282d8efCe846A88B159800bd4130ad77443Fa1A1 ) . We may need to add this in the doc : how to add the mOcean token in metamask
![image](https://user-images.githubusercontent.com/26000280/108981445-67e1fb80-7695-11eb-83a8-7143ca8e281e.png)
![image](https://user-images.githubusercontent.com/26000280/108982043-08d0b680-7696-11eb-9208-ddd145877067.png)

2. In the matic wallet i have 0.1 matic and 300 mOcean
![image](https://user-images.githubusercontent.com/26000280/108981609-9069f580-7695-11eb-9be5-36422868404a.png)
![image](https://user-images.githubusercontent.com/26000280/108981683-a5468900-7695-11eb-9d33-bdff4ce52f69.png)
3. in the matic explorer i have 
![image](https://user-images.githubusercontent.com/26000280/108981746-b55e6880-7695-11eb-841f-115808a3b764.png)

So apparently the wallets see matic as eth 
Also users may be concerned when they see the value of mOcean as 0$ ( img from pt 2 ), we may need to explain this as well somewhere

**Comment by DimitarSD** [comment]
> how to add the mOcean token in metamask or better, implement the add to metamask feature

Add to MetaMask might be a better approach. 

> Metamask shows that i have 0.1 eth

I think that by default they give us 0.1 MATIC on your first deposit (transfer from ETH). However, on my side, everything's OK in MetaMask. The icon is the same though:

![matic-eth](https://user-images.githubusercontent.com/8516866/108992979-9ca87f80-76a2-11eb-8923-27f63c039843.png)

**Comment by trentmc** [comment]
️‍🔥

**Comment by kremalicious** [comment]
![giphy](https://user-images.githubusercontent.com/90316/111466243-52577300-8723-11eb-909e-c0cef04f2dca.gif)
