### ISSUE TITLE
Easily bridge ERC20 datatokens between Eth mainnet & polygon

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/multi-repo-issue#94]
**Background / motivation**

In Q1 2021, we deployed Ocean to Polygon, side-by-side with Eth mainnet. [multirepo#77](https://github.com/oceanprotocol/multi-repo-issue/issues/77), [blog post](https://blog.oceanprotocol.com/ocean-on-polygon-network-8abad19cbf47).

In Q2 2021, the goal is for Ocean Market to see data assets across >1 networks at once. [multirepo#67](https://github.com/oceanprotocol/multi-repo-issue/issues/67). 

Beyond that, we want: make it easy for users to bridge EC20 datatokens between Eth mainnet and Polygon. That's the aim of this issue. 

Options for the bridge itself:
- use existing staking-based bridge run by the Polygon team. Would need to work with them so that datatokens are allowed, without needing manual intervention for each new datatoken.
- Ocean having its own staking-based bridge,
- use Anyswap / Fusion, an existing AMM-based bridge where 1 token pool is on Eth mainnet and the other is in Polygon
- use a Balancer AMM-based bridge, working with Balancer team
- more

What may help: Q2 2021 work on Ocean V4, which includes rethinking where we store metadata (and relation to NFT work). 

**TODOs**

- [ ] Flesh out this TODO list further
- [ ] Have an Eth mainnet <> polygon bridge that supports Ocean datatokens. See options above
- [ ] (if we want it) Can bridge datatokens from within Ocean Market
- [ ] _(add to me)_
