### ISSUE TITLE
Deprecate 'price' endpoints in DDO, update components accordingly

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/multi-repo-issue#96]
Summary: remove "price" from DDO because it doesn't make sense, and ocean sw arch finally allows us.

Details: Aquarius DDO currently has "price" for each given data asset. It dates to Ocean V1 & V2. This doesn't make sense for V3 because a data asset could have >1 markets (pools, etc) each with its own price etc. We reluctantly kept in "price" as a placeholder to help get us going when we shipped Ocean Market in V3. Since that time we've brought in TheGraph for a lot of stats. It can also be used for price info. Furthermore, Ocean Market will be more flexible in support of >1 markets [multi-repo-issue#59](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/multi-repo-issue/59). So we're now in a position to, and motivated to, deprecate "price" from DDO

**TODOs first**
- [x] Market: Remove `price` from queries [market#498](https://github.com/oceanprotocol/market/issues/498)
- [x] Market: Fetch price without relying on `ddo.price`  [market#497](https://github.com/oceanprotocol/market/issues/497)
- [x] Market: New `Highest Liquidity` component [market#496](https://github.com/oceanprotocol/market/issues/496)
- [x] Market: Show tabs without relying on `ddo.price.type` [market#499](https://github.com/oceanprotocol/market/issues/499) 

**TODOs next****
- [x] Aquarius: Deprecate price endpoints [aquarius#329](https://github.com/oceanprotocol/aquarius/issues/329)

The following have been closed because we don't need to do them
- Aquarius `get_asset_ddo(did)` method causes `ResourceWarning: unclosed socket` [aquarius#420]( https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/aquarius/420)
